# -*- coding: utf-8 -*-
"""StreamlitDashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNeCf8P4_zU1ANVWlfKjfsw43251Jltb
"""

!pip install -q streamlit
import streamlit as st
st.write("Hello world")